apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    name: postgresql
spec:
  ports:
    - name: postgresql
      port: 5432
      targetPort: postgresql
  selector:
    name: postgresql
