kind: Deployment
apiVersion: apps/v1
metadata:
  name: zookeeper
  labels:
    app: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
      name: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
        name: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: thecloudgarage/k8s-springboot-kafka-order-management:zookeeper
        ports:
        - containerPort: 2181
        env:
        - name: ZOOKEEPER_ID
          value: "1"
        - name: ZOOKEEPER_SERVER_1
          value: zookeeper
